function [dimensions] = dimensionarg(settings, areaparameters)
	%DIMENSIONARG return coder type for dimension argument of compiled functions
	%	Input:
	%		settinge:		structure with compilation settings
	%		areaparameters:	coder type for area parameters
	%	Output:
	%		dimensions:		coder type for dimensions argument
	max_system_states = settings.max_system_states;
	max_system_controls = settings.max_system_controls;
	max_system_measurements = settings.max_system_measurements;
	max_system_references = settings.max_system_references;
	max_number_of_systems = settings.max_number_of_systems;
	max_number_of_area_functions = settings.max_number_of_area_functions;
	dimensions = struct(...
		'models',						coder.typeof(int32(1)),...
		'states',						coder.typeof(int32(1)),...
		'controls',						coder.typeof(int32(1)),...
		'measurements',					coder.typeof(int32(1)),...
		'measurements_xdot',			coder.typeof(int32(1)),...
		'references',					coder.typeof(int32(1)),...
		'tf_structure',					coder.typeof(1, [max_system_references, max_system_references], [true, true]),...
		'number_decouplingconditions',	coder.typeof(int32(1), [max_system_references, 1], [true, false]),...
		'V_invariant',					coder.typeof(1, [max_number_of_systems, max_system_states, max_system_states, max_system_references], [true, true, true, true]),...
		'm_invariant',					coder.typeof(int32(1), [max_system_references, 1], [true, false]),...
		'hasfeedthrough_decoupling',	coder.typeof(true, [max_system_references, 1], [true, false]),...
		'descriptor',					coder.typeof(true),...
		'isdiscrete',					coder.typeof(true),...
		'areas_max',					coder.typeof(int32(1)),...
		'area_args',					coder.typeof(int32(1), [max_number_of_systems, 1], [true, false]),...
		'area_parts',					coder.typeof(int32(1), [max_number_of_systems, 1], [true, false]),...
		'area_hasgrad',					coder.typeof(true, 1, 1),...
		'area_hashess',					coder.typeof(true, 1, 1),...
		'area_parameters',				coder.typeof(areaparameters, [max_number_of_systems, max_number_of_area_functions], [true, true]),...
		'R_fixed_has',					coder.typeof(true),...
		'R_fixed_only',					coder.typeof(true),...
		'R_fixed_constraints',			coder.typeof(int32(1)),...
		'R_fixed',						coder.typeof(true, [max_system_controls, max_system_measurements], [true, true]),...
		'R_fixed_values',				coder.typeof(1, [max_system_controls, max_system_measurements], [true, true]),...
		'R_fixed_A',					coder.typeof(1, [max_system_controls*max_system_measurements - 1, max_system_controls*max_system_measurements], [true, true]),...
		'R_fixed_b',					coder.typeof(1, [max_system_controls*max_system_measurements - 1, 1], [true, false]),...
		'R_fixed_T',					coder.typeof(1, [max_system_controls*max_system_measurements - 1, max_system_controls*max_system_measurements - 1], [true, true]),...
		'R_fixed_T_inv',				coder.typeof(1, [max_system_controls*max_system_measurements - 1, max_system_controls*max_system_measurements - 1], [true, true]),...
		'R_isforced2zero',				coder.typeof(true),...
		'K_fixed_has',					coder.typeof(true),...
		'K_fixed_only',					coder.typeof(true),...
		'K_fixed_constraints',			coder.typeof(int32(1)),...
		'K_fixed',						coder.typeof(true, [max_system_controls, max_system_measurements], [true, true]),...
		'K_fixed_values',				coder.typeof(1, [max_system_controls, max_system_measurements], [true, true]),...
		'K_fixed_A',					coder.typeof(1, [max_system_controls*max_system_measurements - 1, max_system_controls*max_system_measurements], [true, true]),...
		'K_fixed_b',					coder.typeof(1, [max_system_controls*max_system_measurements - 1, 1], [true, false]),...
		'K_fixed_T',					coder.typeof(1, [max_system_controls*max_system_measurements - 1, max_system_controls*max_system_measurements - 1], [true, true]),...
		'K_fixed_T_inv',				coder.typeof(1, [max_system_controls*max_system_measurements - 1, max_system_controls*max_system_measurements - 1], [true, true]),...
		'K_isforced2zero',				coder.typeof(true),...
		'F_fixed_has',					coder.typeof(true),...
		'F_fixed_only',					coder.typeof(true),...
		'F_fixed_constraints',			coder.typeof(int32(1)),...
		'F_fixed',						coder.typeof(true, [max_system_controls, max_system_references], [true, true]),...
		'F_fixed_values',				coder.typeof(1, [max_system_controls, max_system_references], [true, true]),...
		'F_fixed_A',					coder.typeof(1, [max_system_controls*max_system_references - 1, max_system_controls*max_system_references], [true, true]),...
		'F_fixed_b',					coder.typeof(1, [max_system_controls*max_system_references - 1, 1], [true, false]),...
		'F_fixed_T',					coder.typeof(1, [max_system_controls*max_system_references - 1, max_system_controls*max_system_references - 1], [true, true]),...
		'F_fixed_T_inv',				coder.typeof(1, [max_system_controls*max_system_references - 1, max_system_controls*max_system_references - 1], [true, true]),...
		'F_isforced2zero',				coder.typeof(true),...
		'RKF_fixed_has',				coder.typeof(true),...
		'RKF_fixed_only',				coder.typeof(true),...
		'RKF_fixed_constraints',		coder.typeof(int32(1)),...
		'RKF_fixed',					coder.typeof(true, [max_system_controls, 2*max_system_measurements + max_system_references], [true, true]),...
		'RKF_fixed_values',				coder.typeof(1, [max_system_controls, 2*max_system_measurements + max_system_references], [true, true]),...
		'RKF_fixed_A',					coder.typeof(1, [max_system_controls*(2*max_system_measurements + max_system_references) - 1, max_system_controls*(2*max_system_measurements + max_system_references)], [true, true]),...
		'RKF_fixed_b',					coder.typeof(1, [max_system_controls*(2*max_system_measurements + max_system_references) - 1, 1], [true, false]),...
		'RKF_fixed_T',					coder.typeof(1, [max_system_controls*(2*max_system_measurements + max_system_references) - 1, max_system_controls*(2*max_system_measurements + max_system_references) - 1], [true, true]),...
		'RKF_fixed_T_inv',				coder.typeof(1, [max_system_controls*(2*max_system_measurements + max_system_references) - 1, max_system_controls*(2*max_system_measurements + max_system_references) - 1], [true, true]),...
		'index_R_free',					coder.typeof(true, [max_system_controls*(2*max_system_measurements + max_system_references), 1], [true, false]),...
		'index_K_free',					coder.typeof(true, [max_system_controls*(2*max_system_measurements + max_system_references), 1], [true, false]),...
		'index_F_free',					coder.typeof(true, [max_system_controls*(2*max_system_measurements + max_system_references), 1], [true, false]),...
		'index_RKF_free',				coder.typeof(true, [max_system_controls*(2*max_system_measurements + max_system_references), 1], [true, false]),...
		'index_all_free',				coder.typeof(true, [max_system_controls*(2*max_system_measurements + max_system_references), 1], [true, false])...
	);
end