name: Automerge
on:
  [push,pull_request]:
    branches-ignore:
      - master
      - development
    paths:
      - 'docs/svgs/*'
      - 'README.md'
      - 'README.tex.md'
      - 'README.md.tex'

jobs:
  merge:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: "pascalgn/automerge-action@v0.8.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "Status:Automerge,Feature:Documentation,!wip,!work in progress"
          MERGE_REMOVE_LABELS: "Status:Automerge"
          MERGE_METHOD: "rebase"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_DELETE_BRANCH: "true"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "merge"
