name: Automerge
on:
  push:
    branches-ignore:
      - master
      - development
    paths:
      - 'docs/svgs/*'
      - 'README.md'
      - 'README.tex.md'
      - 'README.md.tex'
  pull_request:
    branches-ignore:
      - master
      - development
    paths:
      - 'docs/svgs/*'
      - 'README.md'
      - 'README.tex.md'
      - 'README.md.tex'

jobs:
  merge:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      # set environment variables for linters
      - name: Set Environment
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "MERGE_LABELS=Status:Automerge,Feature:Documentation,!wip,!work in progress" >> $GITHUB_ENV
          echo "MERGE_REMOVE_LABELS=Status:Automerge" >> $GITHUB_ENV
          echo "MERGE_METHOD=rebase" >> $GITHUB_ENV
          echo "MERGE_COMMIT_MESSAGE=automatic" >> $GITHUB_ENV
          echo "MERGE_FORKS=false" >> $GITHUB_ENV
          echo "MERGE_RETRIES=6" >> $GITHUB_ENV
          echo "MERGE_RETRY_SLEEP=10000" >> $GITHUB_ENV
          echo "MERGE_DELETE_BRANCH=true" >> $GITHUB_ENV
          echo "UPDATE_LABELS=" >> $GITHUB_ENV
          echo "UPDATE_METHOD=merge" >> $GITHUB_ENV
      - name: Wait for status checks
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1"
        with:
          ignoreActions: Automerge,Generate Documentation
          checkInterval: 40
      - name: Automerge
        if: steps.waitforstatuschecks.outputs.status == 'success'
        uses: "pascalgn/automerge-action@v0.8.5"
