name: EditorConfig-Action
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: EditorConfig lint
      uses: reviewdog/action-eclint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN  }}
        reporter: github-pr-review
