name: Linting
on:
  [push, pull_request]

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: YAML Lint
        uses: bewuethr/yamllint-action@v1
        with:
          file_or_dir: .
          config-file: .github/workflows/linters.yamllint
      - name: shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2181 -e SC2039
