name: Linting
on:
  [push, pull_request_target]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # set environment variables for linters
      - name: Set Environment
        run: |
          echo "{EC_FIX_ERROR}={false}" >> $GITHUB_ENV
          echo "{ALWAYS_LINT_ALL_FILES}={false}" >> $GITHUB_ENV
          echo "{SHELLCHECK_OPTS}={-e SC2181 -e SC2039 -e SC2162 -e SC1091}" >> $GITHUB_ENV
      - name: YAML Lint
        uses: bewuethr/yamllint-action@v1
        with:
          # file_or_dir: .
          config-file: .github/workflows/linters.yamllint
      - name: shellcheck
        uses: ludeeus/action-shellcheck@v1
      - name: EditorConfig
        uses: zbeekman/EditorConfig-Action@master
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1
      - name: flake8 Lint
        uses: py-actions/flake8@v1.0.1
        with:
          exclude: ".svn,CVS,.bzr,.hg,.git,lib/optimization/NLOPT/interface/NLOPT/*"
      - name: Update status
        if: ${{ github.event_name == 'pull_request' }}
        uses: ouzi-dev/commit-status-updater@v1
        with:
          status: "${{ job.status }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.workflow }}
