name: Markdown Math
on:
  pull_request:
    branches-ignore:
      - '**-docs'
    paths:
      - 'docs/svgs/*'
      - 'README.md'
      - 'README.tex.md'
      - 'README.md.tex'

jobs:
  texify:
    # Check if the PR is not from a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && !endsWith(github.head_ref, '-docs') }}
    name: Generate Documentation
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      # checkout repository
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACCESS_TOKEN_BRANCHPROTECTION }}
      - name: Install latex packages
        run: |
          apt-get install sudo
          tlmgr init-usertree
          sudo tlmgr install $(xargs < ./.github/actions/texify_markdown/texlive.packages)
      # - name: Setup miktex container
      #  uses: ./.github/actions/texify_markdown
      # install python
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      # install python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # regenerate all images for master and development
      - name: Clear image cache
        if: ${{ github.event_name == 'pull_request' && (github.ref == 'master' || github.ref == 'development') }}
        run: |
          rm -rf docs/svgs/*.svg
      # run tex conversion for pull request
      - name: Texify
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          sh docs/markdown_gitlab2github.sh "$GITHUB_BASE_REF"
      # commit changes for pull request
      - name: Create Pull Request for documentation changes
        id: createPR
        uses: peter-evans/create-pull-request@v3.1.0
        with:
          token: ${{ secrets.ACCESS_TOKEN_BRANCHPROTECTION }}
          commit-message: "updates math for documentation"
          committer: pvogt09 <50047961+pvogt09@users.noreply.github.com>
          author: pvogt09 <50047961+pvogt09@users.noreply.github.com>
          title: updates math for documentation
          body: This is an auto-generated PR which updates math for documentation for pull request into branch `${{ github.base_ref }}`.
          branch: ${{ github.head_ref }}-docs
          signoff: true
          labels: Feature:Documentation,Status:Automerge
#      - name: Commit changed documentation
#        if: ${{ github.event_name == 'pull_request' }}
#        uses: EndBug/add-and-commit@v4
#        with:
#          message: "updates math for documentation"
#          add: "docs/* README.md"
#          signoff: true
#          ref: ${{ github.head_ref }}
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Commit changed documentation
#        run: |
#          if !(git diff --quiet --exit-code docs && git diff --quiet --exit-code README.md); then git add docs/\*; git add README.md; git commit -m "updates math for documentation" --signoff; fi
