function [objectiveoption_prototype] = objectiveoptions_prototype_decoupling(number_references)
	%OBJECTIVEOPTIONS_PROTOTYPE_DECOUPLING return prototype structure for decoupling control objective options
	%	Input:
	%		number_references:			number of references
	%	Output:
	%		objectiveoption_prototype:	prototype for decoupling control objective options
	objectiveoption_prototype = struct(...
		'tf_structure',					NaN(number_references, number_references),...
		'decouplingstrategy',			GammaDecouplingStrategy.getDefaultValue(),...
		'sortingstrategy_decoupling',	GammaDecouplingconditionSortingStrategy.getDefaultValue(),...
		'weight_decoupling',			1,...
		'weight_prefilter',				1,...
		'tolerance_decoupling',			NaN,...
		'tolerance_prefilter',			NaN,...
		'solvesymbolic',				true,...
		'round_equations_to_digits',	NaN,...
		'allowoutputdecoupling',		false...
	);
end